In [6]:
from tensorflow import keras

In [14]:
layer= keras.layers.Dense(100, activation="elu",
                         kernel_initializer="he_normal",
                         kernel_regularizer=keras.regularizers.L2(0.01))

# for elastic regularizer kernel_regularizer=keras.regularizers.l1_l2(0.1,0.01)

In [15]:
model= keras.models.Sequential([
    keras.layers.Flatten(input_shape=[28,28]),
    keras.layers.Dense(300, activation="elu", kernel_initializer="he_normal", kernel_regularizer=keras.regularizers.l2(0.01)),
    
    keras.layers.Dense(100, activation="elu", kernel_initializer="he_normal", kernel_regularizer=keras.regularizers.l2(0.01)),
    keras.layers.Dense(10, activation="Softmax", kernel_regularizer= keras.regularizers.l2(0.01))
    
])

model.compile(loss="sparse_categorical_crossentropy", optimizer="nadam", metrics=["accuracy"])

In [16]:
model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_5 (Flatten)         (None, 784)               0         
                                                                 
 dense_15 (Dense)            (None, 300)               235500    
                                                                 
 dense_16 (Dense)            (None, 100)               30100     
                                                                 
 dense_17 (Dense)            (None, 10)                1010      
                                                                 
Total params: 266610 (1.02 MB)
Trainable params: 266610 (1.02 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [28]:
from functools import partial

RegularizedDense = partial(keras.layers.Dense,
                           activation="elu",
                           kernel_initializer="he_normal", 
                           kernel_regularizer=keras.regularizers.l2(0.01))
model1= keras.models.Sequential([
    keras.layers.Flatten(input_shape=[28,28]),
    RegularizedDense(300),
    RegularizedDense(100),
    RegularizedDense(10, activation="softmax")
])
model1.compile(loss="sparse_categorical_crossentropy", optimizer="nadam", metrics=["accuracy"])

In [29]:
model1.summary()

Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_11 (Flatten)        (None, 784)               0         
                                                                 
 dense_24 (Dense)            (None, 300)               235500    
                                                                 
 dense_25 (Dense)            (None, 100)               30100     
                                                                 
 dense_26 (Dense)            (None, 10)                1010      
                                                                 
Total params: 266610 (1.02 MB)
Trainable params: 266610 (1.02 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


# Max-Norm Regularization

In [32]:
from functools import partial

RegularizedDense = partial(keras.layers.Dense,
                           activation="elu",
                           kernel_initializer="he_normal", 
                           kernel_regularizer=keras.regularizers.l2(0.01), 
                           kernel_constraint=keras.constraints.max_norm(1.))

model2= keras.models.Sequential([
    keras.layers.Flatten(input_shape=[28,28]),
    RegularizedDense(300),
    RegularizedDense(100),
    RegularizedDense(10, activation="softmax")
])

model2.compile(loss="sparse_categorical_crossentropy", optimizer="nadam", metrics=["accuracy"])

# n_epochs = 2
#history= model2.fit(X_train_scaled, y_train, epochs=n_epochs, validation_data=(X_valid_Scaled, y_valid))

In [33]:
7350745153

7350745153

#  Bernouli Random Variable

In [35]:
!pip install tensorflow tensorflow_probability


   ---------------------------------------- 0.0/6.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/6.9 MB 991.0 kB/s eta 0:00:07
    --------------------------------------- 0.1/6.9 MB 1.3 MB/s eta 0:00:06
   - -------------------------------------- 0.3/6.9 MB 2.0 MB/s eta 0:00:04
   -- ------------------------------------- 0.4/6.9 MB 2.0 MB/s eta 0:00:04
   -- ------------------------------------- 0.5/6.9 MB 2.1 MB/s eta 0:00:04
   --- ------------------------------------ 0.6/6.9 MB 2.3 MB/s eta 0:00:03
   ---- ----------------------------------- 0.7/6.9 MB 2.3 MB/s eta 0:00:03
   ---- ----------------------------------- 0.9/6.9 MB 2.3 MB/s eta 0:00:03
   ----- ---------------------------------- 1.0/6.9 MB 2.3 MB/s eta 0:00:03
   ----- ---------------------------------- 1.0/6.9 MB 2.3 MB/s eta 0:00:03
   ------- -------------------------------- 1.3/6.9 MB 2.6 MB/s eta 0:00:03
   -------- ------------------------------- 1.4/6.9 MB 2.7 MB/s eta 0:00:03
   --------- ----

In [1]:
import tensorflow as tf
import tensorflow_probability as tfp

In [2]:
prob = 0.7
r = tfp.distributions.Bernoulli(probs=prob, dtype=tf.float32).sample(sample_shape=(10,1))
r

<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.]], dtype=float32)>

In [3]:
y_pred=tf.random.normal((10,1))
y_pred

<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[-0.27949375],
       [ 1.2450783 ],
       [ 1.3126452 ],
       [ 0.3017487 ],
       [ 0.6178259 ],
       [-0.5525112 ],
       [ 0.23103175],
       [-2.3882408 ],
       [ 1.0612408 ],
       [-0.74793595]], dtype=float32)>

In [4]:
tf.math.multiply(y_pred,r)

<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[-0.27949375],
       [ 1.2450783 ],
       [ 1.3126452 ],
       [ 0.3017487 ],
       [ 0.        ],
       [-0.5525112 ],
       [ 0.23103175],
       [-0.        ],
       [ 1.0612408 ],
       [-0.74793595]], dtype=float32)>

# Dropout Layer

In [7]:
model4=keras.models.Sequential([
    keras.layers.Flatten(input_shape=[28,28]),
    keras.layers.Dropout(rate=0.5),  # Rate 0.5-0.8
    keras.layers.Dense(300, activation="elu",kernel_initializer="he_normal"),
    keras.layers.Dropout(rate=0.5),
    keras.layers.Dense(100, activation="elu", kernel_initializer="he_normal"),
    keras.layers.Dropout(rate=0.5),
    keras.layers.Dense(10,activation="softmax")
    
])

model4.compile(loss="sparse_categorical_crossentropy", optimizer="nadam", metrics=["accuracy"])

In [8]:
model4.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten (Flatten)           (None, 784)               0         
                                                                 
 dropout (Dropout)           (None, 784)               0         
                                                                 
 dense (Dense)               (None, 300)               235500    
                                                                 
 dropout_1 (Dropout)         (None, 300)               0         
                                                                 
 dense_1 (Dense)             (None, 100)               30100     
                                                                 
 dropout_2 (Dropout)         (None, 100)               0         
                                                                 
 dense_2 (Dense)             (None, 10)                1

In [9]:
layer1=tf.keras.layers.Dropout(.3, input_shape=(1,))

In [10]:
layer1

In [11]:
data= tf.random.normal((10,1))
data

<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[-0.7495111 ],
       [ 1.014936  ],
       [ 0.5414842 ],
       [-1.8489008 ],
       [-0.6228965 ],
       [ 0.33343676],
       [ 0.96102124],
       [ 0.9606916 ],
       [-0.9518918 ],
       [-0.2807444 ]], dtype=float32)>

In [12]:
layer1(data, training=True)

<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[-1.0707302 ],
       [ 1.4499086 ],
       [ 0.77354884],
       [-2.6412868 ],
       [-0.88985217],
       [ 0.47633824],
       [ 1.3728875 ],
       [ 1.3724166 ],
       [-1.3598454 ],
       [-0.40106344]], dtype=float32)>

In [14]:
l= tf.keras.layers.Dropout(.1, input_shape=(1,))

In [15]:
d=tf.ones((10,1))*5
d

<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[5.],
       [5.],
       [5.],
       [5.],
       [5.],
       [5.],
       [5.],
       [5.],
       [5.],
       [5.]], dtype=float32)>

In [16]:
l(d,training=True)

<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[5.555556],
       [5.555556],
       [5.555556],
       [5.555556],
       [5.555556],
       [5.555556],
       [5.555556],
       [5.555556],
       [5.555556],
       [5.555556]], dtype=float32)>

In [22]:
(1/(1-0.1))*5   #1/1-rate

5.555555555555555